databases:
  - name: evershop-db
    plan: free

services:
  - type: web
    name: evershop
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: APP_URL
        value: https://evershop.onrender.com
      - key: DB_HOST
        fromDatabase:
          name: evershop-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: evershop-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: evershop-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: evershop-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: evershop-db
          property: database
